Use LMAlertView as dynamic framework
lmcd/LMAlertView pull request #66
Opened 2016-05-09 07:03 UTC by BenchR267

This fixes imports to be able to use LMAlertView as an dynamic framework + some code improvements for runtime safety.

2016-09-25 20:12 UTC, apwelsh requested changes
Suggested edit to LMAlertView.m

2016-09-25 20:12 UTC, apwelsh commented on LMAlertView/LMAlertView.h
> +#import "RBBSpringAnimation.h"
I believe the proper FrameWorks notation would be:
#import &lt;RBBAnimation/RBBSpringAnimation.h&gt;

2016-09-25 20:12 UTC, apwelsh commented on LMAlertView/LMAlertView.m
> +#import "CAAnimation+Blocks.h"
Change to:
#import &lt;CAAnimationBlocks/CAAnimation+Blocks.h&gt;

2016-09-26 07:49 UTC, BenchR267 commented on LMAlertView/LMAlertView.h
> +#import "RBBSpringAnimation.h"
It seems like I already updated this one

2017-08-08 14:42 UTC, BenchR267 commented
Any intentions in merging this?

2017-08-08 20:00 UTC, apwelsh commented
I think the project was abandoned.  I ended up pulling in the source directly into my project and integrating the changes, only to drop its use completely for Apple's built in solution.

2017-08-12 22:20 UTC, ztalbot2000 commented
I still use it in my project.  It does what I need and still works in IOS
11.  I had pulled the source long time ago, and do not use it as a
framework.

Ttfn,
John Talbot


On Tue, Aug 8, 2017 at 4:00 PM Armand Welsh <notifications@github.com>
wrote:

> I think the project was abandoned. I ended up pulling in the source
> directly into my project and integrating the changes, only to drop its use
> completely for Apple's built in solution.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lmcd/LMAlertView/pull/66#issuecomment-321065237>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AGQRX_k-wGJsbuBJozEDTCHKaxvz6UDaks5sWL5vgaJpZM4IZ4ev>
> .
>

2018-05-09 19:31 UTC, closed without merging